import json
q = chr(39)

# getFanFaceInfo code block
ffi = [
  "",
  "    // 从模板精确检测扇面位置，返回宽高比 + 每行像素边界（用于二维码精准放置）",
  "    function getFanFaceInfo(tplUrl) {",
  "      return new Promise(resolve => {",
  "        const img = new Image();",
  f"        img.crossOrigin = {q}anonymous{q};",
  "        img.onload = () => {",
  "          try {",
  "            const SC = 4;",
  "            const sw = Math.max(1, Math.round(img.naturalWidth  / SC));",
  "            const sh = Math.max(1, Math.round(img.naturalHeight / SC));",
  f"            const cc = document.createElement({q}canvas{q});",
  "            cc.width = sw; cc.height = sh;",
  f"            cc.getContext({q}2d{q}).drawImage(img, 0, 0, sw, sh);",
  f"            const d  = cc.getContext({q}2d{q}).getImageData(0, 0, sw, sh).data;",
  "            const iW = img.naturalWidth, iH = img.naturalHeight;",
  "            function isDark(i) {",
  "              const p = i * 4;",
  "              return Math.abs(d[p]-17)<=40 && Math.abs(d[p+1]-17)<=40 && Math.abs(d[p+2]-17)<=40;",
  "            }",
  "            const bg = new Uint8Array(sw * sh);",
  "            const q2  = [];",
  "            function seed(x, y) { const i=y*sw+x; if(!bg[i]&&isDark(i)){bg[i]=1;q2.push(i);} }",
  "            for (let x=0;x<sw;x++){seed(x,0);seed(x,sh-1);}",
  "            for (let y=1;y<sh-1;y++){seed(0,y);seed(sw-1,y);}",
  "            for (let qi=0;qi<q2.length;qi++){",
  "              const i=q2[qi],x=i%sw,y=(i/sw)|0;",
  "              if(x>0    &&!bg[i-1] &&isDark(i-1)) {bg[i-1]=1; q2.push(i-1);}",
  "              if(x<sw-1 &&!bg[i+1] &&isDark(i+1)) {bg[i+1]=1; q2.push(i+1);}",
  "              if(y>0    &&!bg[i-sw]&&isDark(i-sw)){bg[i-sw]=1;q2.push(i-sw);}",
  "              if(y<sh-1 &&!bg[i+sw]&&isDark(i+sw)){bg[i+sw]=1;q2.push(i+sw);}",
  "            }",
  "            let sMinX=sw,sMinY=sh,sMaxX=0,sMaxY=0,found=false;",
  "            const sRowXMin = new Array(sh).fill(sw);",
  "            const sRowXMax = new Array(sh).fill(0);",
  "            for (let y=0;y<sh;y++) for (let x=0;x<sw;x++){",
  "              const i=y*sw+x;",
  "              if(!bg[i]&&isDark(i)){",
  "                if(x<sMinX)sMinX=x; if(x>sMaxX)sMaxX=x;",
  "                if(y<sMinY)sMinY=y; if(y>sMaxY)sMaxY=y;",
  "                if(x<sRowXMin[y])sRowXMin[y]=x;",
  "                if(x>sRowXMax[y])sRowXMax[y]=x;",
  "                found=true;",
  "              }",
  "            }",
  "            if (!found||sMaxX<=sMinX||sMaxY<=sMinY) { resolve({ratio:1.0,bbox:null}); return; }",
  "            const minX=sMinX*SC, minY=sMinY*SC;",
  "            const maxX=Math.min(iW-1, sMaxX*SC+SC-1);",
  "            const maxY=Math.min(iH-1, sMaxY*SC+SC-1);",
  "            const rowXMin = new Array(iH).fill(iW);",
  "            const rowXMax = new Array(iH).fill(0);",
  "            for (let sy=0;sy<sh;sy++){",
  "              if (sRowXMin[sy]>=sw) continue;",
  "              const rxMin=sRowXMin[sy]*SC;",
  "              const rxMax=Math.min(iW-1, sRowXMax[sy]*SC+SC-1);",
  "              for (let dy=0;dy<SC;dy++){const oy=sy*SC+dy; if(oy>=iH)break; rowXMin[oy]=rxMin; rowXMax[oy]=rxMax;}",
  "            }",
  "            resolve({ ratio:(maxX-minX+1)/(maxY-minY+1), bbox:{minX,minY,maxX,maxY}, rowXMin, rowXMax });",
  "          } catch { resolve({ratio:1.0,bbox:null}); }",
  "        };",
  f"        img.onerror = () => resolve({{ratio:1.0,bbox:null}});",
  "        img.src = tplUrl;",
  "      });",
  "    }",
  "",
]
getFanFaceInfoCode = "
".join(ffi)
